// <auto-generated />
namespace OnIt.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PriorityDueTimeFieldsTaskModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriorityDueTimeFieldsTaskModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710121748245_Priority-DueTimeFields-TaskModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
